spring.application.name=Basszeit
spring.datasource.url=jdbc:postgresql://dpg-da3buguk1f9s73ei8p2g-a/basszeit_db_asxb
spring.datasource.username=basszeit_db_asxb_user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.time_zone: UTC
spring.jpa.properties.hibernate.show-sql: false
spring.jpa.properties.hibernate.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hibernate.ddl-auto: update
spring.jpa.open-in-view: false
spring.jpa.generate-ddl=true

spring.sql.init.platform= postgres
spring.sql.init.mode: always
